# Generated by Django 5.1.6 on 2025-02-27 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="born_at",
            field=models.DateField(blank=True, null=True, verbose_name="birth date"),
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "discount",
                    models.PositiveIntegerField(verbose_name="discount percent"),
                ),
                ("is_active", models.BooleanField(verbose_name="is active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="discounts",
            field=models.ManyToManyField(
                blank=True, null=True, to="accounts.discount", verbose_name="discounts"
            ),
        ),
    ]
