# Generated by Django 5.1.6 on 2025-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_born_at_discount_and_more"),
        ("library", "0015_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="discounts",
            field=models.ManyToManyField(
                blank=True, null=True, to="library.discount", verbose_name="discounts"
            ),
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
    ]
