# Generated by Django 5.1.6 on 2025-03-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_discounts_delete_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="phone"
            ),
        ),
    ]
